language: generic
services:
  - docker

dist: trusty
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/toolbox .
      - docker images
      - docker push $DOCKER_USERNAME/toolbox
    - stage: test
    - script: docker run --rm $DOCKER_USERNAME/toolbox hey --version